name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test (${{ matrix.go }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.23.x, 1.24.x, "1.x", "1.25.0-rc.1"]
        os: [ubuntu-latest]
        include:
          - go: "1.x"
            os: macos-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies (libpcap-dev)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Run tests
        run: |
          set -ev
          go test github.com/google/gopacket
          go test github.com/google/gopacket/layers
          go test github.com/google/gopacket/tcpassembly
          go test github.com/google/gopacket/reassembly
          go test github.com/google/gopacket/pcapgo
          go test github.com/google/gopacket/pcap
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo $(which go) test github.com/google/gopacket/routing
          fi

  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.x"

      - name: Run gofmt
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "Go code is not formatted, run 'go fmt ./...'" >&2
            exit 1
          fi

      - name: Run govet
        run: |
          if [ -n "$(go vet ./...)"]; then;
            echo "Go code has vet errors, run 'go vet ./...'" >&2
            exit 1
          fi

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: |
          if [ -n "$(golint ./...)" ]; then
            echo "Go code has lint errors, run 'golint ./...'" >&2
            exit 1
          fi
